// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	LINKS: KVNamespace;
	REVERSE_LINKS: KVNamespace;
	LIMITS: KVNamespace;
	ASSETS: Fetcher;
}
