// Generated by Wrangler by running `wrangler types --experimental-include-runtime=./runtime.d.ts`

interface Env {
	LINKS: KVNamespace;
	REVERSE_LINKS: KVNamespace;
	LIMITS: KVNamespace;
	ASSETS: Fetcher;
}
